// Builds the W3C DTCG tokens.tokens.json (web-lab schema) and the runtime CSS variables.
import type { Ramps, Semantic, SemanticName, Step } from './color'
import { STEPS } from './color'
import { FONTS } from './presets'
import { PAIRS } from './contrast'

export interface Knobs {
  accent: string; pin: boolean; tint: number
  customDark: boolean; darkAccent: string; darkSurface: 'deep' | 'soft'
  radius: number; corner: 'round' | 'squircle' | 'sharp'; shadow: 'none' | 'soft' | 'hard' | 'border'; border: number
  font: string; ratio: number; base: number; leading: number
  space: number; width: number
  duration: number; ease: string
}

export const TEXT_STEPS = ['xs', 'sm', 'base', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl', '6xl'] as const

/** Modular type scale in rem from base size and ratio. */
export function typeScale(base: number, ratio: number): Record<(typeof TEXT_STEPS)[number], string> {
  const rem = (n: number) => `${(Math.round((base * Math.pow(ratio, n)) / 16 * 1000) / 1000)}rem`
  return { xs: rem(-2), sm: rem(-1), base: rem(0), lg: rem(1), xl: rem(2), '2xl': rem(3), '3xl': rem(4), '4xl': rem(5), '5xl': rem(6), '6xl': rem(7) }
}

export const SPACE_KEYS = [0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24, 32] as const
export function spacing(unit: number): Record<string, string> {
  const out: Record<string, string> = {}
  for (const k of SPACE_KEYS) out[String(k)] = k === 0 ? '0px' : `${(k * unit) / 16}rem`
  return out
}

export function radii(r: number, corner: Knobs['corner']) {
  const px = (n: number) => `${Math.round(n)}px`
  if (corner === 'sharp') return { none: '0px', sm: '0px', md: '0px', lg: '0px', xl: '0px', full: '0px' }
  return { none: '0px', sm: px(r * 0.5), md: px(r), lg: px(r * 1.5), xl: px(r * 2), full: '9999px' }
}

export function shadows(kind: Knobs['shadow'], border: number) {
  // Recipes from better-ui: layered transparent shadows for depth; a 1px ring as border.
  const soft = {
    sm: '0 1px 2px 0 oklch(0 0 0 / 0.05)',
    md: '0 4px 6px -1px oklch(0 0 0 / 0.08), 0 2px 4px -2px oklch(0 0 0 / 0.06)',
    lg: '0 10px 15px -3px oklch(0 0 0 / 0.1), 0 4px 6px -4px oklch(0 0 0 / 0.08)',
  }
  const hard = { sm: `${border || 1}px ${border || 1}px 0 0 oklch(0 0 0 / 0.9)`, md: '4px 4px 0 0 oklch(0 0 0 / 0.9)', lg: '8px 8px 0 0 oklch(0 0 0 / 0.9)' }
  const ring = {
    sm: '0 0 0 1px oklch(0 0 0 / 0.06)',
    md: '0 0 0 1px oklch(0 0 0 / 0.06), 0 1px 2px -1px oklch(0 0 0 / 0.06), 0 2px 4px 0 oklch(0 0 0 / 0.04)',
    lg: '0 0 0 1px oklch(0 0 0 / 0.08), 0 1px 2px -1px oklch(0 0 0 / 0.08), 0 8px 16px -4px oklch(0 0 0 / 0.1)',
  }
  const none = { sm: 'none', md: 'none', lg: 'none' }
  return { none, soft, hard, border: ring }[kind]
}

export const EASES: Record<string, string> = {
  out: 'cubic-bezier(0.2, 0, 0, 1)',
  'in-out': 'cubic-bezier(0.65, 0, 0.35, 1)',
  spring: 'linear(0, 0.006, 0.025 2.8%, 0.101 6.1%, 0.539 18.9%, 0.721 25.3%, 0.849 31.5%, 0.937 38.1%, 0.968 41.8%, 0.991 45.7%, 1.006 50.1%, 1.015 55%, 1.017 63.9%, 1.001)',
}

const tok = (v: unknown, ext?: Record<string, unknown>) => (ext ? { $value: v, $extensions: { 'web-lab': ext } } : { $value: v })
const group = (type: string, entries: Record<string, string>) =>
  Object.fromEntries([['$type', type], ...Object.entries(entries).map(([k, v]) => [k, tok(v)])])

export function buildTokens(k: Knobs, ramps: Ramps, sem: Semantic) {
  const rampGroup = (r: Record<Step, string>) => Object.fromEntries(STEPS.map((s) => [String(s), tok(r[s])]))
  const semanticColor: Record<string, unknown> = { $type: 'color' }
  for (const [name, v] of Object.entries(sem) as [SemanticName, Semantic[SemanticName]][]) {
    semanticColor[name] = tok(v.lightRef, { dark: v.darkRef })
  }
  semanticColor['primary'] = { $value: '{semantic.color.accent}', $description: 'alias for shadcn; the brand is accent' }
  semanticColor['primary-foreground'] = { $value: '{semantic.color.accent-foreground}', $description: 'alias for shadcn' }
  const f = FONTS[k.font]
  const dur = Math.max(k.duration, 0)
  return {
    $schema: 'https://tr.designtokens.org/format/',
    $description: `web-lab tokens generated by the style lab. Accent ${k.accent}${k.pin ? ' (pinned)' : ' (snapped)'}${ramps['brand-dark'] ? `, dark accent ${k.darkAccent}` : ''}, ${k.corner} corners, ${k.shadow} shadows, ${k.font}. Edit values, not structure.`,
    color: {
      $type: 'color',
      gray: rampGroup(ramps.gray), brand: rampGroup(ramps.brand), red: rampGroup(ramps.red),
      green: rampGroup(ramps.green), amber: rampGroup(ramps.amber),
      ...(ramps['brand-dark'] ? { 'brand-dark': rampGroup(ramps['brand-dark']) } : {}),
      white: tok('#ffffff'), black: tok('#000000'),
    },
    spacing: { $type: 'dimension', $description: `Base ${k.space}. Tailwind generates p-*, m-*, gap-* from these keys.`, ...Object.fromEntries(Object.entries(spacing(k.space)).map(([a, b]) => [a, tok(b)])) },
    text: { $type: 'dimension', $description: `Type scale, base ${k.base}px, ratio ${k.ratio}. Tailwind generates text-*.`, ...Object.fromEntries(Object.entries(typeScale(k.base, k.ratio)).map(([a, b]) => [a, tok(b)])) },
    leading: group('number', { tight: '1.15', snug: String(Math.max(1.25, k.leading - 0.15)), normal: String(k.leading), relaxed: String(k.leading + 0.15) }),
    tracking: group('dimension', { tight: '-0.02em', normal: '0em', wide: '0.04em' }),
    font: { $type: 'fontFamily', sans: tok(f.sans.split(',').map((s) => s.trim().replace(/"/g, ''))), display: tok(f.display.split(',').map((s) => s.trim().replace(/"/g, ''))), mono: tok(f.mono.split(',').map((s) => s.trim().replace(/"/g, ''))) },
    radius: group('dimension', radii(k.radius, k.corner)),
    shadow: group('shadow', shadows(k.shadow, k.border)),
    ease: group('cubicBezier', { out: EASES.out, 'in-out': EASES['in-out'], spring: EASES.spring }),
    duration: group('duration', { fast: `${Math.round(dur * 0.75)}ms`, normal: `${dur}ms`, slow: `${Math.round(dur * 1.5)}ms`, page: `${dur * 2}ms` }),
    breakpoint: group('dimension', { sm: '40rem', md: '48rem', lg: '64rem', xl: '80rem' }),
    semantic: {
      $description: 'Decisions. Aliases to primitives only. Dark mode in $extensions.web-lab.dark.',
      color: semanticColor,
      radius: { $type: 'dimension', control: tok('{radius.md}'), surface: tok('{radius.lg}') },
      duration: { $type: 'duration', ui: tok('{duration.normal}') },
      ease: { $type: 'cubicBezier', ui: tok(`{ease.${k.ease}}`) },
    },
    component: {
      $description: 'Only when a component deviates from the semantic tier. Reference semantic.*',
      button: { $type: 'dimension', height: tok('{spacing.10}'), 'padding-x': tok('{spacing.4}') },
      input: { $type: 'dimension', height: tok('{spacing.10}') },
      'corner-shape': { $type: 'string', $value: k.corner === 'squircle' ? 'squircle' : 'round', $description: 'CSS corner-shape where supported; radius is the fallback.' },
      'border-width': { $type: 'dimension', $value: `${k.border}px` },
    },
    $extensions: {
      'web-lab': {
        $description: 'Text-on-background pairs verified in light and dark. 4.5 normal text, 3 large text, icons and focus. Decorative borders have no WCAG requirement.',
        contrast: PAIRS.map((p) => ({ fg: `semantic.color.${p.fg}`, bg: `semantic.color.${p.bg}`, min: p.min })),
        lab: { accent: k.accent, pin: k.pin, tint: k.tint, customDark: k.customDark, darkAccent: k.darkAccent, darkSurface: k.darkSurface, radius: k.radius, corner: k.corner, shadow: k.shadow, border: k.border, font: k.font, ratio: k.ratio, base: k.base, leading: k.leading, space: k.space, width: k.width, duration: k.duration, ease: k.ease },
      },
    },
  }
}

/** Runtime CSS variables for the preview: same names the python script emits. */
export function cssVars(k: Knobs, ramps: Ramps, sem: Semantic, dark: boolean): Record<string, string> {
  const v: Record<string, string> = {}
  for (const [g, r] of Object.entries(ramps)) for (const s of STEPS) v[`--color-${g}-${s}`] = r[s]
  for (const [name, val] of Object.entries(sem)) { v[`--${name}`] = dark ? val.dark : val.light; v[`--color-${name}`] = `var(--${name})` }
  v['--primary'] = 'var(--accent)'; v['--primary-foreground'] = 'var(--accent-foreground)'
  for (const [a, b] of Object.entries(spacing(k.space))) v[`--spacing-${a}`] = b
  for (const [a, b] of Object.entries(typeScale(k.base, k.ratio))) v[`--text-${a}`] = b
  for (const [a, b] of Object.entries(radii(k.radius, k.corner))) v[`--radius-${a}`] = b
  const sh = shadows(k.shadow, k.border)
  // Dark mode: one white ring instead of layered depth (better-ui).
  if (dark && k.shadow === 'border') { sh.sm = '0 0 0 1px oklch(1 0 0 / 0.08)'; sh.md = '0 0 0 1px oklch(1 0 0 / 0.1)'; sh.lg = '0 0 0 1px oklch(1 0 0 / 0.13)' }
  if (dark && k.shadow === 'hard') { sh.sm = sh.sm.replace('oklch(0 0 0 / 0.9)', 'oklch(1 0 0 / 0.9)'); sh.md = sh.md.replace('oklch(0 0 0 / 0.9)', 'oklch(1 0 0 / 0.9)'); sh.lg = sh.lg.replace('oklch(0 0 0 / 0.9)', 'oklch(1 0 0 / 0.9)') }
  for (const [a, b] of Object.entries(sh)) v[`--shadow-${a}`] = b
  const f = FONTS[k.font]
  v['--font-sans'] = f.sans; v['--font-display'] = f.display; v['--font-mono'] = f.mono
  v['--leading-tight'] = '1.15'; v['--leading-normal'] = String(k.leading); v['--leading-relaxed'] = String(k.leading + 0.15)
  v['--duration-fast'] = `${Math.round(k.duration * 0.75)}ms`; v['--duration-normal'] = `${k.duration}ms`; v['--duration-slow'] = `${Math.round(k.duration * 1.5)}ms`
  v['--ease-ui'] = EASES[k.ease] ?? EASES.out
  v['--border-width'] = `${k.border}px`
  v['--corner-shape'] = k.corner === 'squircle' ? 'squircle' : 'round'
  v['--content-width'] = `${k.width}rem`
  return v
}

export function tokensCss(k: Knobs, ramps: Ramps, sem: Semantic): string {
  // Mirrors skills/design-system/scripts/tokens_to_tailwind.py so the export can be dropped in directly.
  const L: string[] = ['@import "tailwindcss";', '', '/* Generated by the web-lab style lab. Canonical source: tokens.tokens.json (run tokens_to_tailwind.py to regenerate and verify contrast). */', '', '@theme {']
  for (const [g, r] of Object.entries(ramps)) for (const s of STEPS) L.push(`  --color-${g}-${s}: ${r[s]};`)
  L.push('  --color-white: #ffffff;', '  --color-black: #000000;')
  for (const [a, b] of Object.entries(spacing(k.space))) L.push(`  --spacing-${a}: ${b};`)
  for (const [a, b] of Object.entries(typeScale(k.base, k.ratio))) L.push(`  --text-${a}: ${b};`)
  const f = FONTS[k.font]
  L.push(`  --font-sans: ${f.sans};`, `  --font-display: ${f.display};`, `  --font-mono: ${f.mono};`)
  for (const [a, b] of Object.entries(radii(k.radius, k.corner))) L.push(`  --radius-${a}: ${b};`)
  for (const [a, b] of Object.entries(shadows(k.shadow, k.border))) L.push(`  --shadow-${a}: ${b};`)
  for (const [a, b] of Object.entries(EASES)) L.push(`  --ease-${a}: ${b};`)
  L.push(`  --duration-fast: ${Math.round(k.duration * 0.75)}ms;`, `  --duration-normal: ${k.duration}ms;`, `  --duration-slow: ${Math.round(k.duration * 1.5)}ms;`)
  L.push('}', '', '@theme inline {')
  for (const name of Object.keys(sem)) L.push(`  --color-${name}: var(--${name});`)
  L.push('  --color-primary: var(--primary);', '  --color-primary-foreground: var(--primary-foreground);', '}', '', ':root {')
  const refVar = (ref: string) => ref === '{color.white}' ? 'var(--color-white)' : `var(--color-${ref.slice(7, -1).replace('.', '-')})`
  for (const [name, val] of Object.entries(sem)) L.push(`  --${name}: ${refVar(val.lightRef)};`)
  L.push('  --primary: var(--accent);', '  --primary-foreground: var(--accent-foreground);', `  --border-width: ${k.border}px;`, '}', '')
  const darkLines = Object.entries(sem).map(([name, val]) => `  --${name}: ${refVar(val.darkRef)};`)
  L.push('@media (prefers-color-scheme: dark) {', '  :root:not([data-theme="light"]) {', ...darkLines.map((l) => '  ' + l), '  }', '}', '', '[data-theme="dark"] {', ...darkLines, '}', '')
  return L.join('\n')
}
