const {chromium}=require('playwright');
const assert=require('assert');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:8770');
 await page.locator('.card').first().waitFor();
 assert(await page.locator('#pageSummary').innerText());
 const data=await (await page.request.get('http://localhost:8770/api/assets')).json();
 const a=data.assets.find(a=>a.type==='image'&&a.result);
 assert(a,'Need an existing image result for comparison');
 await page.locator('#fQ').fill(a.file.split('/').pop());
 const row=page.locator(`.card[data-id="${a.id}"]`);
 await row.waitFor();
 const prev=await row.locator('.presets button[aria-pressed="true"]').getAttribute('data-preset');
 const different=row.locator(`.presets button:not([data-preset="${prev}"])`).first();
 await different.click();
 assert((await row.locator('.pending-state').innerText()).includes('Falta optimizar'));
 await row.locator(`button[data-preset="${prev}"]`).click();
 await row.getByRole('button',{name:'Comparar',exact:true}).click();
 await page.locator('#workDialog').waitFor();
 assert.equal(await page.locator('.compare-panes figure').count(),2);
 await page.getByRole('button',{name:'100%',exact:true}).click();
 assert(await page.locator('.compare-panes').evaluate(el=>el.classList.contains('pixel')));
 await page.screenshot({path:'/tmp/walo-compare.png'});
 await page.locator('#workDialog .close-dialog').click();
 await row.getByRole('button',{name:'Historial',exact:true}).click();
 await page.locator('.history-row').first().waitFor();
 await page.screenshot({path:'/tmp/walo-history.png'});
 await page.locator('#workDialog .close-dialog').click();
 await page.locator('#fQ').fill('');
 const video=data.assets.find(a=>a.type==='video'&&a.result);
 if(video) {
  const ranged=await page.request.get('http://localhost:8770/result/'+video.id,{headers:{Range:'bytes=0-63'}});
  assert.equal(ranged.status(),206);assert.equal((await ranged.body()).length,64);
  await page.locator('#fQ').fill(video.file.split('/').pop());
  await page.locator(`.card[data-id="${video.id}"]`).getByRole('button',{name:'Comparar',exact:true}).click();
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('#workDialog video')).every(v=>v.readyState>=1));
  await page.locator('.play-pair').click();
  await page.waitForFunction(()=>Array.from(document.querySelectorAll('#workDialog video')).every(v=>v.currentTime>.1));
  await page.locator('.play-pair').click();
  assert(await page.locator('#workDialog video').evaluateAll(vs=>Math.abs(vs[0].currentTime-vs[1].currentTime)<.5));
  await page.locator('#workDialog .close-dialog').click();
  await page.locator('#fQ').fill('');
 }
 await page.locator('#fPage').selectOption('projects__illustration');
 const expected=data.assets.filter(a=>a.pages.includes('projects__illustration')).length;
 assert.equal(await page.locator('.card').count(),expected);
 await page.screenshot({path:'/tmp/walo-overview.png'});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/tmp/walo-mobile.png'});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow');
 assert.deepEqual(errors,[]);
 console.log('PASS: filter includes shared assets; selection/dirty state; comparison 100%; synchronized video + byte ranges; history; mobile width; no JS errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
